// <auto-generated />
using Dam.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Dam.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Dam.Domain.DamEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Capacity");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Dams");
                });

            modelBuilder.Entity("Dam.Domain.DamSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("DamId");

                    b.Property<DateTime>("Date");

                    b.Property<decimal>("Storage");

                    b.HasKey("Id");

                    b.HasIndex("DamId");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("Dam.Domain.DamSnapshot", b =>
                {
                    b.HasOne("Dam.Domain.DamEntity", "Dam")
                        .WithMany()
                        .HasForeignKey("DamId");
                });
#pragma warning restore 612, 618
        }
    }
}
